### ISSUE TITLE
您的客户端版本与服务器不匹配

### ISSUE THREAD

**Issue by zhuhy051** [alk3p/EasyConnect-767#1]
系统环境为manjaro linux。
使用`makepkg`和`sudo pacman -U easyconnect-7.6.7.3-4-x86_64.pkg.tar.xz`命令后完成easyconnect的安装后遇到如下问题：
`Pango-ERROR **: 10:34:10.684: Harfbuzz version too old (1.3.1)`
使用AUR中给出的方法
```
curl -JOL http://ftp.acc.umu.se/pub/GNOME/sources/pango/1.42/pango-1.42.4.tar.xz
tar xf pango-1.42.4.tar.xz
cd pango-1.42.4
./configure --prefix=/usr
make && make DESTDIR="~/oldlib/pango" install

LD_LIBRARY_PATH=~/oldlib/pango/usr/lib /usr/share/sangfor/EasyConnect/EasyConnect
```
问题解决，但是打开后输入地址时提示“您的客户端版本与服务器不匹配，请下载更新”。
如果按照AUR中的操作回退PKGBUILD的版本到
http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb
则在登录easyconnect后会立刻闪退。

**Comment by alk3p** [comment]
您可以注意到，PKGBUILD中有构建`pango-1.42.4`，这里是借鉴了AUR中的处理，因而正常情况下`Harfbuzz version`应该已经得到解决。
关于客户端版本不匹配的问题，目前已知EasyConnect有767和linux_01两种版本，建议check一下EasyConnect服务端提供的下载链接，linux_01版建议直接`yaourt -S easyconnect`安装AUR版本。
如仍有疑问，欢迎提issue :)

**Comment by zhuhy051** [comment]
感谢回复！
检查过服务端下载链接后，我确认了客户端应该安装的版本为linux_01版，但是在安装后运行的过程中终端出现了如下错误：
`(node:5977) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
`
在命令前添加sudo也不能解决这一问题，导致在登录成功十秒左右easyconnect就自动关闭。
不知道您对这一问题有什么看法呢

**Comment by alk3p** [comment]
客气。
aur上也有人提到这个，刚刚试着复现，系统版本`Manjaro 19.0 Kyria`，运行正常。
从您提供的报错信息来看，应该是node异步回调的问题，属于程序运行时错误。EasyConnect是闭源商业软件，因而暂时没有解决方案。
建议向EasyConnect的开发商feedback一下 :)
