### ISSUE TITLE
Do you have a version for ubuntu18?

### ISSUE THREAD

**Issue by JincanDeng** [alk3p/EasyConnect-767#3]

**Comment by alk3p** [comment]
Packages are provided **officially** for those distributions which support Debian Packager or RedHat Package Manager.
You may consult your domain administrator for `.deb` package compatible with server version. Normally, it will be one of the following:
http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_767/EasyConnect_x64_7_6_7_3.deb
http://download.sangfor.com.cn/download/product/sslvpn/pkg/linux_01/EasyConnect_x64.deb
