### ISSUE TITLE
编译过程中遇到一个问题，大佬帮忙看看

### ISSUE THREAD

**Issue by liuxian1990** [alk3p/EasyConnect-767#6]
FAILED: pango/Pango-1.0.typelib
/usr/bin/g-ir-compiler pango/Pango-1.0.gir --output pango/Pango-1.0.typelib
/usr/bin/g-ir-compiler: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
ninja: build stopped: subcommand failed.
==> 错误： 在 build() 中发生一个错误。
    正在放弃...

**Comment by alk3pInjection** [comment]
检查一下`libffi`和`lib32-libffi`是否已安装。
如仍无效，请以合适权限执行如下命令：
```
ln -s /usr/lib32/libffi.so /usr/lib32/libffi.so.7
ln -s /usr/lib/libffi.so /usr/lib/libffi.so.7
```
